### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by KrabbyBuckets** [twopg/Dashboard#5]
it says this. i just pulled, and now it says this. didnt change anything.

**Comment by theADAMJR** [comment]
Are you starting the dashboard with `ng serve`?

**Comment by KrabbyBuckets** [comment]
> Are you starting the dashboard with `ng serve`?

@theADAMJR Yes I Am

**Comment by KrabbyBuckets** [comment]
@theADAMJR if you know why this happening lmk

**Comment by KrabbyBuckets** [comment]
ima just use tsx
